controllers/PlanetsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\PlanetsModel;
use app\models\PlanetsSearchModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PlanetsController implements the CRUD actions for PlanetsModel model.
 */
class PlanetsController extends Controller {

    public $defaultAction = 'index';

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PlanetsModel models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new PlanetsSearchModel();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PlanetsModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the PlanetsModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PlanetsModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = PlanetsModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionReport($count = 0) {
        $dataProvider = \app\models\PlanetsResidentsModel::getCountPeopleOnPlanet($count);
        return $this->render('report', [
                    'dataProvider' => $dataProvider,
                    'count' => $count,
        ]);
    }


}

controllers/ResidentsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ResidentsModel;
use app\models\ResidentsSearchModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ResidentsController implements the CRUD actions for ResidentsModel model.
 */
class ResidentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ResidentsModel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ResidentsSearchModel();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ResidentsModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    /**
     * Finds the ResidentsModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ResidentsModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ResidentsModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/planets/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PlanetsSearchModel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="planets-model-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'rotation_period') ?>

    <?= $form->field($model, 'orbital_period') ?>

    <?= $form->field($model, 'diameter') ?>

    <?php // echo $form->field($model, 'climate') ?>

    <?php // echo $form->field($model, 'gravity') ?>

    <?php // echo $form->field($model, 'terrain') ?>

    <?php // echo $form->field($model, 'surface_water') ?>

    <?php // echo $form->field($model, 'population') ?>

    <?php // echo $form->field($model, 'url') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/planets/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\URL;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PlanetsSearchModel */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Planets Models';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="planets-model-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            [
                'label' => 'Название',
                'format' => 'raw',
                'value' => function ($data) {
                    return Html::a(Html::encode($data->name), Url::toRoute(['planets/view', 'id' => $data->id]));
                },
            ],
            'rotation_period',
            'orbital_period',
            'diameter',
        //'climate',
        //'gravity',
        //'terrain',
        //'surface_water',
        //'population',
        ],
    ]);
    ?>
</div>

views/planets/report.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\URL;

$this->title = 'Отчет';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Отчет о планетах  <?= empty($count) ? " без персонажей" : "содержащих персонажей в кол-ве {$count}" ?></h1>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-6">
                <?=
                GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        [
                            'label' => 'Планета',
                            'format' => 'raw',
                            'value' => function ($data) {
                                //  return Html::a(Html::encode($data->planets->name), Url::toRoute(['planets/view', 'id' => $data->planets->id]));
                                return Html::a(Html::encode($data->planetsBySqlRelation->name), Url::toRoute(['planets/view', 'id' => $data->planetsBySqlRelation->id]));
                            },
                        ],
                    ],
                ]);
                ?>
            </div>


        </div>

    </div>
</div>

views/planets/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\URL;

/* @var $this yii\web\View */
/* @var $model app\models\PlanetsModel */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Planets Models', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="planets-model-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'rotation_period',
            'orbital_period',
            'diameter',
            'climate',
            'gravity',
            'terrain',
            'surface_water',
            'population',
        ],
    ])
    ?>

    <? if (!empty($model->residents)): ?>
        <h2><?= Html::encode('Персонажи на планете') ?></h1>
            <table>
                <tbody>

                    <? foreach ($model->residents as $item): ?>
                        <tr>
                            <td>

                                <?= Html::a(Html::encode($item->name), Url::toRoute(['residents/view', 'id' => $item->id])); ?>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>           
        <? endif; ?>

</div>